# Generated by Django 2.0.5 on 2018-05-31 13:50

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('balance', models.DecimalField(decimal_places=10, default=Decimal('0'), max_digits=20)),
                ('currency', models.CharField(choices=[('USD', 'USD'), ('PHP', 'PHP')], max_length=3)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
